### PR TITLE
[TECH-956] feature/tech-956-eslint-action-exclude-deleted-file

### PR DESCRIPTION
**Pull request by kend77**
Just a reminder: github's graphql api interface does not return information about file status. This uses the REST interface to get that info. I kept the gql call here because it does a nice job of gathering nodes for a specific Github resource, specifically the last commit.

### CODE REVIEW

**Comment by boxfoot** [comment]
What's the difference between this and #1 which I just reviewed?

**Comment by kend77** [comment]
> What's the difference between this and #1 which I just reviewed?

@boxfoot Sorry. I wanted to rename the branch to match the tech ticket. The changes are the same. Sorry about that!

**Comment by kend77** [comment]
@boxfoot It looks like the version number is kept up to date with the version in the `package.json`. I think I should update the package json to v 1.0.2, then get this merged, tag the master branch with `v.1.0.2`, and release the version. Then we can update the workflow in `Glidian` to match the new release.

Does that make sense?

**Comment by sliu198** [comment]
@kend77 I believe you can bump the version with `npm version patch`. I think we should do that after merging though. And yes, we can then update the workfloww in Glidian

**Comment by kend77** [comment]
@sliu198 It doesn't look like the current version of the repo was bumped. It still lists the version as `1.0.0`. Maybe the tag was created directly with `git tag`?

**Review by sliu198 — APPROVED** [review]
LGTM as well, I suggest we merge and tag this, then open a PR on Glidian to test it.

**Comment by sliu198** [comment]
@kend77 ohh, actually it's because v1.0.1 was not based off master - I had trouble getting master to work IIRC. There's a release/v1.0.x branch, could you rebase your commit to that branch? I think the package.js is up to date there.

**Comment by sliu198** [comment]
cherry-pick, not rebase - apologies.

**Comment by kend77** [comment]
@sliu198 Updated to point to the release branch!

**Comment by sliu198** [comment]
@kend77 Feel free to merge and version, then open a PR in Glidian using the new version. I think we'll want to test that it's still working as intended. I vaguely recall needing to create a Github Release in order for other repos to pull it in, but I'm not sure. Could you try and document?

**Pull request merged**
